"""
Exports the annotated image + full chat transcript as a downloadable PDF.
Implements the bonus "Exportable report" requirement from Section 5.

Enhanced version: includes detection summary table, per-object attributes,
image metadata, and improved formatting.
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import List, Tuple

from PIL import Image
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas


def build_pdf_report(
    annotated_image: Image.Image,
    caption: str,
    chat_history: List[Tuple[str, str]],
    detections: List | None = None,
    original_image: Image.Image | None = None,
) -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4
    margin = 2 * cm

    # ---- Header ----
    c.setFillColor(HexColor("#1a1a2e"))
    c.rect(0, height - 1.8 * cm, width, 1.8 * cm, fill=1, stroke=0)
    c.setFillColor(HexColor("#ffffff"))
    c.setFont("Helvetica-Bold", 18)
    c.drawString(margin, height - 1.3 * cm, "🛰️ GeoQuery — Session Report")
    c.setFont("Helvetica", 9)
    c.setFillColor(HexColor("#cccccc"))
    c.drawRightString(width - margin, height - 1.3 * cm, datetime.now().strftime("%Y-%m-%d %H:%M"))

    c.setFillColor(HexColor("#000000"))
    y = height - 2.5 * cm

    # ---- Caption ----
    c.setFont("Helvetica-Bold", 11)
    c.drawString(margin, y, "Image Caption")
    y -= 16
    c.setFont("Helvetica-Oblique", 10)
    for line in _wrap(caption, 90):
        c.drawString(margin + 0.3 * cm, y, line)
        y -= 13
    y -= 6

    # ---- Annotated image ----
    img_reader = ImageReader(annotated_image)
    max_w = width - 2 * margin
    max_h = 8 * cm
    iw, ih = annotated_image.size
    scale = min(max_w / iw, max_h / ih)
    draw_w, draw_h = iw * scale, ih * scale
    y -= draw_h
    c.drawImage(img_reader, margin, y, width=draw_w, height=draw_h)
    y -= 10

    # ---- Detection summary ----
    if detections:
        y -= 10
        c.setFont("Helvetica-Bold", 11)
        c.drawString(margin, y, f"Detected Objects ({len(detections)})")
        y -= 16

        # Table header
        c.setFont("Helvetica-Bold", 9)
        c.setFillColor(HexColor("#f0f0f0"))
        c.rect(margin, y - 2, width - 2 * margin, 14, fill=1, stroke=0)
        c.setFillColor(HexColor("#000000"))
        c.drawString(margin + 5, y, "Class")
        c.drawString(margin + 120, y, "Confidence")
        c.drawString(margin + 220, y, "Relative Size")
        c.drawString(margin + 340, y, "Dominant Color")
        y -= 16

        c.setFont("Helvetica", 9)
        from utils.image_utils import crop_box, dominant_color_name, relative_size_label
        src_img = original_image or annotated_image
        for det in sorted(detections, key=lambda d: -d.confidence):
            if y < margin + 20:
                c.showPage()
                y = height - margin
                c.setFont("Helvetica", 9)

            try:
                crop = crop_box(src_img, det.box)
                color = dominant_color_name(crop)
                size = relative_size_label(det.box, src_img)
            except Exception:
                color = "—"
                size = "—"

            c.drawString(margin + 5, y, det.label.capitalize())
            c.drawString(margin + 120, y, f"{det.confidence:.0%}")
            c.drawString(margin + 220, y, size)
            c.drawString(margin + 340, y, color)
            y -= 14

    # ---- Conversation ----
    y -= 16
    if y < margin + 40:
        c.showPage()
        y = height - margin

    c.setFont("Helvetica-Bold", 11)
    c.drawString(margin, y, "Conversation Transcript")
    y -= 18
    c.setFont("Helvetica", 9)

    for role, text in chat_history:
        prefix = "👤 You: " if role == "user" else "🤖 GeoQuery: "
        for line in _wrap(prefix + text, 95):
            if y < margin:
                c.showPage()
                y = height - margin
                c.setFont("Helvetica", 9)
            c.drawString(margin + 0.3 * cm, y, line)
            y -= 13
        y -= 4  # Extra spacing between messages

    # ---- Footer ----
    c.setFont("Helvetica", 7)
    c.setFillColor(HexColor("#999999"))
    c.drawString(margin, 1 * cm, "Generated by GeoQuery — IIT Ropar Mock Inter IIT Tech Meet 15.0")
    c.drawRightString(width - margin, 1 * cm, "All models run locally • No commercial APIs used")

    c.save()
    buf.seek(0)
    return buf.read()


def _wrap(text: str, width: int) -> List[str]:
    import textwrap
    return textwrap.wrap(text, width=width) or [""]
